#pragma once

#include "defines_generic.h"

#define IPC_STATE_CONNECTING 0
#define IPC_STATE_READING 1
#define IPC_STATE_WRITING 2
#define IPC_INSTANCE_NUM 4
#define IPC_BUFSIZE 4096	// In bytes

#define IPC_MSGDIRECTION_CLIENTTOSERVER 0x80000000
#define IPC_MSGDIRECTION_SERVERTOCLIENT 0x00000000
#define IPC_MSGDIRECTION_MASK 0x80000000

#define IPC_MSGTYPE_MASK (IPC_MSGDIRECTION_MASK - 1)

#define IPC_MSGTYPE_WSTR 0x1

#define IPC_MSGTYPE_GETHOSTBYFAKEIPV4 0x11
#define IPC_MSGTYPE_GETHOSTBYFAKEIPV6 0x12

#define IPC_MSGTYPE_GETFAKEIPV4BYHOST 0x21
#define IPC_MSGTYPE_GETFAKEIPV6BYHOST 0x22
#define IPC_MSGTYPE_RESPHOST 0x2F

#define IPC_MSGTYPE_RESPIPS 0x30
#define IPC_MSGTYPE_RESPIPV4 0x31
#define IPC_MSGTYPE_RESPIPV6 0x32

#define IPC_MSGTYPE_CHILDDATA 0x40
#define IPC_MSGTYPE_QUERYSTORAGE 0x41

#define IPC_MSGTAG_INVALID 0x0

#define MsgIsC2S(x) (((*(PXCH_UINT32*)(x)) & IPC_MSGDIRECTION_MASK) == IPC_MSGDIRECTION_CLIENTTOSERVER)
#define MsgIsS2C(x) (((*(PXCH_UINT32*)(x)) & IPC_MSGDIRECTION_MASK) == IPC_MSGDIRECTION_SERVERTOCLIENT)
#define MsgIsType(type, x) (((*(PXCH_UINT32*)(x)) & IPC_MSGTYPE_MASK) == IPC_MSGTYPE_##type)
#define MsgIsInvalid(x) ((*(PXCH_UINT32*)(x)) == IPC_MSGTAG_INVALID)

#define SetMsgC2S(x) *((PXCH_UINT32*)(x)) = (*((PXCH_UINT32*)(x)) & ~IPC_MSGDIRECTION_MASK) | IPC_MSGDIRECTION_CLIENTTOSERVER
#define SetMsgS2C(x) *((PXCH_UINT32*)(x)) = (*((PXCH_UINT32*)(x)) & ~IPC_MSGDIRECTION_MASK) | IPC_MSGDIRECTION_SERVERTOCLIENT
#define SetMsgInvalid(x) (*(PXCH_UINT32*)(x)) = IPC_MSGTAG_INVALID

typedef const char CIPC_MSGBUF[IPC_BUFSIZE];
typedef char IPC_MSGBUF[IPC_BUFSIZE];

#pragma pack(push, 1)
typedef struct _IPC_MSGHDR_WSTR {
	PXCH_UINT32 u32Tag;
	PXCH_UINT32 cchLength;
} IPC_MSGHDR_WSTR;

#pragma pack(pop)

PXCH_UINT32 IpcCommunicateWithServer(const IPC_MSGBUF sendMessage, PXCH_UINT32 cbSendMessageSize, IPC_MSGBUF responseMessage, PXCH_UINT32* pcbResponseMessageSize);
PXCH_UINT32 WstrToMessage(IPC_MSGBUF chMessageBuf, PXCH_UINT32* pcbMessageSize, const wchar_t* szWstr);
PXCH_UINT32 MessageToWstr(wchar_t* wstr, CIPC_MSGBUF chMessageBuf, PXCH_UINT32 cbMessageSize);
